version: '3.8'

services:
  database:
    container_name: database
    image: postgres:16
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    command: -p 5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=edtech_club'
      - 'POSTGRES_PASSWORD=1234'

  backend:
    image: 'tarinskaya/edtech-app-backend:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - database
    ports:
      - 3001:8081
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:postgresql://database:5432/edtech_club",
              "spring.datasource.username" : "postgres",
              "spring.datasource.password" : "1234",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
              "spring.jpa.hibernate.ddl-auto" : "update",
              "server.port": "3001",
              "server.address": "0.0.0.0"
            }'

  frontend:
    container_name: frontend
    image: frontend
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "npm", "start", "--force" ]